keys:
  - &private-ssh age1w0r39x5z0ye2wcml5e5q6nt8zp7zplndagnl58arvjupdk6qm54shyshqz
  - &yoga age1xdsx6ydssutcjrnyj4h023qtyfuqryswqlucqnc5j5utjnfcjdmq2twlz8
  - &svp age1z8hzw73nftxarapkty90lttnuyv5mmqxarhhl8jmlply6g455v8safhfc5
  - &rmt age19e79dxz6fnkgpy0vrcd2s0aan2l3qcc5hap3wtat2yx3r09zuy9s69sf47
creation_rules:
  - path_regex: nixos/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *private-ssh
          - *yoga
          - *svp
          - *rmt
