set windows-shell := ["powershell.exe", "-c"]

_default:
    @just --choose

ff-betterfox:
    iwr "https://ghfast.top/https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js" -o "user.js" ; \
    Get-Content ff-pref.js | Add-Content user.js
    Move-Item user.js $env:APPDATA\Mozilla\Firefox\Profiles
    ii $env:APPDATA\Mozilla\Firefox\Profiles
    Write-Host "`n about:support`n" -ForegroundColor Green

emacs-mklink:
    Start-Process -Verb RunAs Invoke-Item -FilePath ".\scripts\mklink-emacs-admin.cmd"

emacsclient-shortcut-startup:
    .\scripts\shortcut-emacsclient.ps1

kanata-shortcut-startup:
    .\scripts\shortcut-kanata.ps1

emacs-ob-tangle:
    emacs -Q --batch \
    -l org \
    --eval '(setq vc-follow-symlinks nil)' \
    --eval '(org-babel-tangle-file \"~/.config/emacs/all-emacs.org\")'

singbox-mihomo-setup:
    # Download
    iwr "https://ghfast.top/https://github.com/winsw/winsw/releases/latest/download/WinSW-x64.exe" -O winsw.exe
    iwr "https://ghfast.top/https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip" -O dist.zip
    Expand-Archive -Path "dist.zip"; mi "dist\dist" "ui"; ri "dist.zip", "dist"
    # Create directory
    New-Item $HOME\subs\state -ItemType Directory -Force
    Move-Item ui $HOME\subs\state
    # Copy services
    Copy-Item ..\mofa\config.yaml $HOME\subs
    Copy-Item sb-service.xml, mihomo-service.xml $HOME\subs
    Copy-Item winsw.exe $HOME\subs\sb-service.exe
    Copy-Item winsw.exe $HOME\subs\mihomo-service.exe
    Remove-Item winsw.exe
