set windows-shell := ["powershell.exe", "-c"]

_default:
    @just --choose

ff-betterfox:
    iwr "https://ghfast.top/https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js" -o "user.js" ; \
    Get-Content ff-pref.js | Add-Content user.js
    Move-Item user.js $env:APPDATA\Mozilla\Firefox\Profiles -Force
    ii $env:APPDATA\Mozilla\Firefox\Profiles
    Write-Host "`n about:support`n" -ForegroundColor Green

emacs-mklink:
    Start-Process -Verb RunAs Invoke-Item -FilePath ".\scripts\mklink-emacs-admin.cmd"

kanata-shortcut-startup:
    .\scripts\shortcut-kanata.ps1

emacs-ob-tangle:
    emacs -Q --batch \
      -l org \
      --eval '(setq vc-follow-symlinks nil)' \
      --eval '(org-babel-tangle-file \"~/.config/emacs/all-emacs.org\")'
