# press: i

# 预设一套高质量渲染设置
# 性能不够建议注释
profile=gpu-hq

# 更现代的渲染后端
# vo=gpu-next 默认设置
hwdec=vulkan
gpu-api=vulkan

# save-position-on-quit=yes

# 快进时左上角显示进度消息
osd-on-seek=msg

# 禁用系统缩放，让 mpv 自己处理
hidpi-window-scale=no

# [pyradio]
# volume=80
