# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  ydict = {
    pname = "ydict";
    version = "v2.2.0";
    src = fetchgit {
      url = "https://github.com/TimothyYe/ydict";
      rev = "v2.2.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1rix5dncfk3jffi9zrhc20zy5147v5l8rsiqi86lb4qikdfyq66f";
    };
  };
}
